site_name: moo-rs
site_author: Andrés Sandoval
site_description: Multi-objective optimization using genetic algorithms in Rust and Python.
use_directory_urls: false

theme:
  language: en
  logo: images/moors-logo.png
  favicon: images/moors-logo.png
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  highlightjs: true
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - toc.follow

repo_url: https://github.com/andresliszt/moo-rs
repo_name: "andresliszt/moo-rs"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  # - pymdownx.highlight:
  #     linenums: true
  - pymdownx.arithmatex:
      generic: true
  - neoteroi.cards
  - neoteroi.timeline
  - neoteroi.projects
extra_javascript:
  - js/custom_mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Getting Started:
    - Python:
      - Installation: getting_started/python/installation.md
      - Quick Start: getting_started/python/quick_start.md
      - Knapsack Problem: getting_started/python/knapsack.md
      - Real-Valued Problem: getting_started/python/real_valued.md
    - Rust:
      - Installation: getting_started/rust/installation.md
      - Quick Start: getting_started/rust/quick_start.md
      - Knapsack Problem: getting_started/rust/knapsack.md
      - Real-Valued Problem: getting_started/rust/real_valued.md
  - User Guide:
    - Fitness & Constraints:
      - Overview: user_guide/fitness_and_constraints/fitness_and_constraints.md
      - Python:
        - Fitness Function: user_guide/fitness_and_constraints/python/fitness.md
        - Inequality Constraints: user_guide/fitness_and_constraints/python/ineq_constraints.md
        - Equality Constraints: user_guide/fitness_and_constraints/python/eq_constraints.md
        - Bounds: user_guide/fitness_and_constraints/python/lower_upper_bounds.md
      - Rust:
        - Fitness Function: user_guide/fitness_and_constraints/rust/fitness.md
        - Inequality Constraints: user_guide/fitness_and_constraints/rust/ineq_constraints.md
        - Equality Constraints: user_guide/fitness_and_constraints/rust/eq_constraints.md
        - Bounds: user_guide/fitness_and_constraints/rust/lower_upper_bounds.md
    - Genetic Operators:
      - Overview: user_guide/operators/operators.md
      - Python:
        - Sampling: user_guide/operators/python/sampling.md
        - Crossover: user_guide/operators/python/crossover.md
        - Mutation: user_guide/operators/python/mutation.md
        - Selection: user_guide/operators/python/selection.md
        - Survival: user_guide/operators/python/survival.md
      - Rust:
        - Sampling: user_guide/operators/rust/sampling.md
        - Crossover: user_guide/operators/rust/crossover.md
        - Mutation: user_guide/operators/rust/mutation.md
        - Selection: user_guide/operators/rust/selection.md
        - Survival: user_guide/operators/rust/survival.md
    - Duplicates Cleaner:
      - Overview: user_guide/duplicates/duplicates.md
      - Python:
        - Exact: user_guide/duplicates/python/exact.md
        - Close: user_guide/duplicates/python/close.md
        - Custom: user_guide/duplicates/python/custom.md
      - Rust:
        - Exact: user_guide/duplicates/rust/exact.md
        - Close: user_guide/duplicates/rust/close.md
        - Custom: user_guide/duplicates/rust/custom.md
    - Algorithms:
      - Introduction:
        - Overview: user_guide/algorithms/introduction/introduction.md
        - Python: user_guide/algorithms/introduction/python-introduction.md
        - Rust: user_guide/algorithms/introduction/rust-introduction.md
      - Custom Algorithms:
        - Overview: user_guide/algorithms/custom/custom.md
        - Python: user_guide/algorithms/custom/python-custom.md
        - Rust: user_guide/algorithms/custom/rust-custom.md
      - NSGA-II:
        - Python: user_guide/algorithms/python/nsga2.md
        - Rust: user_guide/algorithms/rust/nsga2.md
      - NSGA-III:
        - Python: user_guide/algorithms/python/nsga3.md
        - Rust: user_guide/algorithms/rust/nsga3.md
      - IBEA:
        - Python: user_guide/algorithms/python/ibea.md
        - Rust: user_guide/algorithms/rust/ibea.md
      - SPEA-II:
        - Python: user_guide/algorithms/python/spea2.md
        - Rust: user_guide/algorithms/rust/spea2.md
      - AGE-MOEA:
        - Python: user_guide/algorithms/python/agemoea.md
        - Rust: user_guide/algorithms/rust/agemoea.md
      - RNSGA-II:
        - Python: user_guide/algorithms/python/rnsga2.md
        - Rust: user_guide/algorithms/rust/rnsga2.md
      - REVEA:
        - Python: user_guide/algorithms/python/revea.md
        - Rust: user_guide/algorithms/rust/revea.md
  - Development:
    - Environment Setup: development/setup_environment.md
    - Algorithm Setup: development/setup_algorithm.md
    - From moors to pymoors: development/from_moors_to_pymoors.md
  - API Reference:
    - Python API: reference.md
    - Rust API (docs.rs): https://docs.rs/moors/latest/moors/

plugins:
  - mkdocs-jupyter
  - search
  - include-markdown
  - macros:
      module_name: docs/macros
extra:
  moors_crate_version: 0.2.9
