[project]
name = "moo-rs-docs"
version = "0.1.0"
requires-python = ">=3.10"

[dependency-groups]
docs = [
    "matplotlib",
    "mkdocs",
    "mkdocs-jupyter",
    "mkdocs-material",
    "pymdown-extensions",
    "neoteroi-mkdocs",
    "mkdocs-include-markdown-plugin",
    "mkdocs-macros-plugin",
    "mkdocstrings",
    "mkdocstrings-python",
]
