[package]
name = "moors"
version = "0.2.10"
edition = "2024"
authors = ["Andrés Sandoval Abarca <andres.sndbrca@gmail.com>"]
description = "Solving multi-objective optimization problems using genetic algorithms."
license = "MIT"
repository = "https://github.com/andresliszt/moo-rs"

[lib]
name = "moors"
crate-type = ["cdylib", "rlib"]

[dependencies]
rand = "0.9.2"
rand_distr = "0.5.1"
num-traits = "0.2.19"
ndarray = "0.16.1"
ordered-float = "5.0.0"
ndarray-stats = "0.6.0"
faer-ext = { version = "0.7.1", features = ["ndarray"] }
faer =  { version = "0.23.1", default-features = false, features = ["std"] }
thiserror = "2.0.17"
derive_builder = "0.20.2"
paste = "1.0.15"

[dev-dependencies]
criterion = "0.5.1"
rstest = "0.26.1"
codspeed-criterion-compat = "4"

[[bench]]
name = "fds"
path = "benches/fds.rs"
harness = false

[[bench]]
name = "dtlz2"
path = "benches/dtlz2.rs"
harness = false

[[bench]]
name = "zdt1"
path = "benches/zdt1.rs"
harness = false

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage,coverage_nightly)'] }

[profile.dev]
incremental = true

[profile.test]
incremental = true

[profile.coverage]
inherits = "release"
codegen-units = 1
lto = false
